### ISSUE TITLE
Name of `chemlab.core.chemical.BalanceSolver.dijkstra`

### ISSUE THREAD

**Issue by ruslangaripov** [ruslangaripov/ChemLab#20]
There is `chemlab.core.chemical.BalanceSolver.dijkstra` method.
What it does is finding a next possible permutation in sequence of numbers using generation in lexicographic order.
*Dijkstra's algorithm* is an algorithm for finding the shortest paths between nodes in a graph.
So my question is: why get the method named "dijkstra"?

And I have the same question about `chemlab.core.chemical.BalanceSolver.inversion` method. It **doesn't** calculate the inverse of matrix but only calculates the matrix of cofactors. It stays one step before the inverse of matrix.

Should we rename the methods I've mentioned? :question:

**Comment by Serg-Norseman** [comment]
You can safely rename. These names are from the original, from which I gathered all this...

**Comment by ruslangaripov** [comment]
OK! I will.

**Comment by ruslangaripov** [comment]
commit 8774af0 fixes the ticket.
